/**
 * NOTE: This class is auto generated by the swagger code generator program (2.4.29).
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */
package org.lifstools.mztab2.server.api;

import com.fasterxml.jackson.databind.ObjectMapper;
import io.swagger.annotations.*;
import java.io.IOException;
import org.springframework.http.ResponseEntity;
import org.springframework.validation.annotation.Validated;
import org.springframework.web.bind.annotation.PathVariable;
import org.springframework.web.bind.annotation.RequestBody;
import org.springframework.web.bind.annotation.RequestHeader;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestMethod;
import org.springframework.web.bind.annotation.RequestParam;
import org.springframework.web.bind.annotation.RequestPart;
import org.springframework.web.multipart.MultipartFile;

import javax.validation.Valid;
import javax.validation.constraints.*;
import java.util.List;
import java.util.Optional;
import javax.servlet.http.HttpServletRequest;
import org.lifstools.mztab2.model.MzTab;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import org.springframework.http.HttpStatus;
@javax.annotation.Generated(value = "io.swagger.codegen.languages.SpringCodegen", date = "2022-12-02T17:14:56.294Z")

@Validated
@Api(value = "convert", description = "the convert API")
@RequestMapping(value = "/mztabvalidator/rest/v2/")
public interface ConvertApi {
    
    Logger log = LoggerFactory.getLogger(ConvertApi.class);

    default Optional<ObjectMapper> getObjectMapper() {
        return Optional.empty();
    }

    default Optional<HttpServletRequest> getRequest() {
        return Optional.empty();
    }

    default Optional<String> getAcceptHeader() {
        return getRequest().
            map(r ->
                r.getHeader("Accept"));
    }
    
    @ApiOperation(value = "", nickname = "convertMzTabFile", notes = "Converts an mzTab file in JSON or XML format to the tab-separated representation. If this method returns an error code 422, the provided file did not pass validation. ", response = String.class, tags={ "convert", })
    @ApiResponses(value = { 
        @ApiResponse(code = 200, message = "Conversion Okay", response = String.class),
        @ApiResponse(code = 415, message = "Unsupported content type"),
        @ApiResponse(code = 422, message = "Invalid input"),
        @ApiResponse(code = 200, message = "Unexpected error") })
    @RequestMapping(value = "/convert",
        produces = { "application/json" }, 
        consumes = { "text/tab-separated-values", "text/plain" },
        method = RequestMethod.POST)
    default ResponseEntity<String> convertMzTabFile(@ApiParam(value = "mzTab file that should be validated." ,required=true )  @Valid @RequestBody MzTab mztabfile) {
        String accept = getAcceptHeader().get();
        if (accept != null && accept.contains("application/json")) {
            try {
                return new ResponseEntity<String>(getObjectMapper().get().readValue("{  \"bytes\": [],  \"empty\": true}", String.class), HttpStatus.NOT_IMPLEMENTED);
            } catch (IOException e) {
                log.error("Couldn't serialize response for content type application/json", e);
                return new ResponseEntity<String>(HttpStatus.INTERNAL_SERVER_ERROR);
            }
        }

        return new ResponseEntity<String>(HttpStatus.NOT_IMPLEMENTED);
    }

}
