/**
 * NOTE: This class is auto generated by the swagger code generator program (2.4.29).
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */
package org.lifstools.mztab2.server.api;

import com.fasterxml.jackson.databind.ObjectMapper;
import org.lifstools.mztab2.model.MzTab;
import io.swagger.annotations.*;
import java.io.IOException;
import org.springframework.http.ResponseEntity;
import org.springframework.validation.annotation.Validated;
import org.springframework.web.bind.annotation.RequestBody;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestMethod;

import javax.validation.Valid;
import java.util.Optional;
import javax.servlet.http.HttpServletRequest;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import org.springframework.http.HttpStatus;
@javax.annotation.Generated(value = "io.swagger.codegen.languages.SpringCodegen", date = "2022-12-02T17:14:56.294Z")

@Validated
@Api(value = "convertPlain", description = "the convertPlain API")
@RequestMapping(value = "/mztabvalidator/rest/v2/")
public interface ConvertPlainApi {

    Logger log = LoggerFactory.getLogger(ConvertPlainApi.class);

    default Optional<ObjectMapper> getObjectMapper() {
        return Optional.empty();
    }

    default Optional<HttpServletRequest> getRequest() {
        return Optional.empty();
    }

    default Optional<String> getAcceptHeader() {
        return getRequest().
            map(r ->
                r.getHeader("Accept"));
    }
    
    @ApiOperation(value = "", nickname = "convertPlainMzTabFile", notes = "Converts an mzTab file in tab separated format to XML or JSON representation. If this method returns an error code 422, the provided file did not pass validation. ", response = MzTab.class, tags={ "convertPlain", })
    @ApiResponses(value = { 
        @ApiResponse(code = 200, message = "Conversion Okay", response = MzTab.class),
        @ApiResponse(code = 415, message = "Unsupported content type"),
        @ApiResponse(code = 422, message = "Invalid input"),
        @ApiResponse(code = 200, message = "Unexpected error") })
    @RequestMapping(value = "/convertPlain",
        produces = { "text/tab-separated-values" }, 
        consumes = { "application/json", "application/xml" },
        method = RequestMethod.POST)
    default ResponseEntity<MzTab> convertPlainMzTabFile(@ApiParam(value = "mzTab file that should be converted." ,required=true )  @Valid @RequestBody String mztabfile) {
        String accept = getAcceptHeader().get();
        if (accept != null && accept.contains("")) {
            try {
                return new ResponseEntity<MzTab>(getObjectMapper().get().readValue("", MzTab.class), HttpStatus.NOT_IMPLEMENTED);
            } catch (IOException e) {
                log.error("Couldn't serialize response for content type ", e);
                return new ResponseEntity<MzTab>(HttpStatus.INTERNAL_SERVER_ERROR);
            }
        }

        return new ResponseEntity<MzTab>(HttpStatus.NOT_IMPLEMENTED);
    }

}
